version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resumate_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001' # MinIO Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
